###
# Testes Locais
# Cep Válido. Deve retornar Código 200 e o Response Body
# no formato: { "temp_C": 28.5, "temp_F": 28.5, "temp_K": 28.5 }
GET http://localhost:8000/32450000

###
# Cep INVÁLIDO (com formato incorreto). Deve retornar Código 422 
# e a mensagem "invalid zipcode"
GET http://localhost:8000/324500000

###
# Cep com formato válido, mas não encontrado. Deve retornar Código 404 
# e a mensagem "can not find zipcode"
GET http://localhost:8000/00000000